import Head from "next/head";
import { api } from "~/utils/api";
import { SubmitHandler, useForm } from "react-hook-form";

export default function Home() {
  const { data: all } = api.atoms.getAll.useQuery();

  const { mutate } = api.atoms.create.useMutation();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<A>();

  type A = Parameters<typeof mutate>["0"];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit((data) => mutate(data))}>
        <input
          {...register("atomicNumber")}
          placeholder="atomic number"
          type="number"
        />
        <input {...register("symbol")} placeholder="Symbol" />
        <input {...register("block.full")} placeholder="block.full" />
        <input {...register("block.shorten")} placeholder="block.shorten" />
        <input
          {...register("block.group")}
          placeholder="block.group"
          type="number"
        />
        <input {...register("discovery.by")} placeholder="discovered by" />
        <input {...register("discovery.year")} placeholder="discovery year" />
        <div className="flex items-center gap-2">
          <input {...register("family.isMetal")} type="checkbox" />
          <p>family isMetal?</p>
        </div>
        <input {...register("family.name")} placeholder="family.name" />
        <input {...register("name.fr")} placeholder="name.fr" />
        <input {...register("name.en")} placeholder="name.en" />

        <button type="submit">envoa nigger</button>
      </form>

      <main>
        <pre>{JSON.stringify(all, null, 2)}</pre>
      </main>
    </>
  );
}
