POST http://localhost:3000/atoms/create HTTP/1.1
content-type: application/json

{
  "atomicNumber": 3,
  "symbol": "Li",
  "name": {
    "en": "Lithium",
    "fr": "Lithium"
  },
  "phaseAtSTP": "solid",
  "block": "s",
  "discovery": {
    "by": "Johan August Arfwedson",
    "country": "Sweden",
    "year": 1817
  },
  "family": {
    "isMetal": true,
    "name": "Alkali metal"
  },
  "group": 1,
  "period": 2
}