### Root

GET http://localhost:4222/atoms/

###

### By atomic number
GET http://localhost:4222/atoms/byAtomicNumber/5

### By internal ID
GET http://localhost:4222/atoms/byId/65732ca900610b6289d60fc8

###

### By discovery year - before
GET http://localhost:4222/atoms/byDiscoveryYear/before/1800

### By discovery year - after
GET http://localhost:4222/atoms/byDiscoveryYear/after/1950

###

### By phase - gas
GET http://localhost:4222/atoms/byPhaseAtSTP/gas
### By phase - liquid
GET http://localhost:4222/atoms/byPhaseAtSTP/liquid
### By phase - solid
GET http://localhost:4222/atoms/byPhaseAtSTP/solid

###

### By metals
GET http://localhost:4222/atoms/metals

###

### By block
GET http://localhost:4222/atoms/byBlock/:block

### 

### By period
GET http://localhost:4222/atoms/byPeriod/:period

###

### Random
GET http://localhost:4222/atoms/random