name: Deploy
on:
  push:
    branches: [master]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Installing dependencies with pnpm
        run: pnpm i --frozen-lockfile
